### ISSUE TITLE
Is it possible to implement FTM protocal based on this project?

### ISSUE THREAD

**Issue by crownz-sec** [open-sdr/openwifi#121]
FTM protocal is used for ranging, details can be found here:https://www.researchgate.net/publication/328327674_Verification_Accuracy_Evaluation_of_WiFi_Fine_Time_Measurements_on_an_Open_Platform.
I just want to know is it possible to implement FTM protocal based on this project?

**Comment by weiliu1011** [comment]
The referenced work uses Intel WiFi card, which does a lot of ranging calculation in the firmware. openwifi currently does not have these supported. 

In addition they also use a different Linux kernel than openwifi, in order to use the iwl driver, so some more challenges can appear.

In short this needs quite some time and effort.

**Comment by JiaoXianjun** [comment]
Yes. It is possible. 

We have some results on synchronisation (not ranging, but basic concept is related). Checkout IEEE Transactions on Industrial Informatics. “Hardware Efficient Clock Synchronization across Wi-Fi and Ethernet Based Network Using PTP” on the publication page.

**Comment by crownz-sec** [comment]
Thanks for kind reply!
