### ISSUE TITLE
Is it possible to support consumer level SDR devices

### ISSUE THREAD

**Issue by ReimuNotMoe** [open-sdr/openwifi#14]
Is it possible to support consumer level SDR devices? Such as BladeRF, LimeSDR, etc.

Of course there's no way to implement hardware CSMA/CA on those devices. But that shouldn't be a big deal with faster computers / realtime scheduling.

**Comment by JiaoXianjun** [comment]
Hi,
This is a very interesting question. Maybe you already find that all the platforms we currently use have fair big FPGA on board. However the HackRF, BladeRF, LImeSDR only have quite small FPGA on board.

openwifi implements not only CSMA/CA on FPGA, but also full physical layer signal processing ( OFDM modulation, demodulation, etc) on FPGA. The reason why we implement all functionalities of Low MAC and layer below on FPGA is because of SIFS:
https://en.wikipedia.org/wiki/Short_Interframe_Space

With computer, the realtime SIFS is very hard.

If you do not care about real-time full stack, you can use BladeRF, LImeSDR, HackRF etc together with this project: gr-ieee802-11:
https://github.com/bastibl/gr-ieee802-11
