### ISSUE TITLE
How can I get timestamp based on TSF when I use tcpdump to catch the packets on board?

### ISSUE THREAD

**Issue by GuanLiliang** [open-sdr/openwifi#169]
When I use tcpdump, I can get timestamp like this, 
![image](https://user-images.githubusercontent.com/92432416/167749940-0ed4230f-b8df-4d40-9323-b4e8cf5980ca.png)
Is this based on TSF? I don't think it is. Maybe it is based on starting up time.
If not, how can I get it based on TSF?

**Comment by gxhen** [comment]
u can transfer the captured .pacp file from the board to your PC via SSH. Then use Wireshark to analyze it. TSF timestamp is in the 802.11 radio information.

**Comment by CaptainiFalcon** [comment]
I am learning 802.11* protocal recently. I think the things about time synchronization is interesting.

When I followed the instructions  in [csi.md](https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/csi.md) to capture CSI and ran “test_side_info_file_display.m”, I got the timestamps as shown below.

![figure1](https://user-images.githubusercontent.com/46293421/171201046-7eb23291-47a6-4f9c-8fc3-d5c3f7bddb7b.png)

The unit of it's value is us, （18,000,000 us = 18 second;  28,000,000 us =28 second）so it seem like that the timestamp in CSI (side_info.txt) is timeing from when I setup the 'sdr0' in board by running ‘wgd.h' (but not from when the ubuntu system boot in board).

After a while, I captured CSI again, and got :

![figure2](https://user-images.githubusercontent.com/46293421/171198268-ff2ca050-7335-4b96-894c-2161372fa21d.png)
(1600000000 us=26.6666667 minute)

And I saw [timestamp in packet sniffer ](https://github.com/open-sdr/openwifi/issues/139#issuecomment-1051988468) is set by 'openwifi_rx_interrupt()', so I think the timestamp in packet sniffer is the time of Untuntu system (in board) that can be got by running 'date' in the shell of ubuntu in board and it's something like '2022-01-25 00:20:29'(the date in my system is that). 

Actually, the timestamp in tcpdump run in my board is "2022-01-25 **:**:**), same as what I thought. 

In short, I don't understand "If you want to relate the CSI information to the WiFi packet, you need to capture WiFi packets (tcpdump/wireshark/etc) while capturing CSI. Then you can match the timestamp (TSF timer value) between WiFi packet and CSI information, because this is the unique same identity of a Wifi packet and related CSI information." in [csi.md](https://github.com/open-sdr/openwifi/blob/master/doc/app_notes/csi.md).

Specifically, I don't understand what is "timestamp (TSF timer value) betweem WiFi packet and CSI". The differnece of timestamp in CSI and packet sniffer is beyond my knowledge.

And I also want to know how to align the time in CSI and packet sniffer.

Apologies for asking some basic question and the English is not standard.

I am looking forward for your reply, thank you very much.

**Comment by JiaoXianjun** [comment]
You have timestamp (in us) on the csi data. You also have timestamp (in us) on the wifi packet captured by packet sniffer (as in the screenshot at the beginning of this issue). They are in the same timeline (both are based on tsf timer). So you can know the relation between csi data and the packet.

**Comment by CaptainiFalcon** [comment]
Understood.

Now, the problem change to "align ONE CSI to the corresponding packet".  I think it is difficult and hava no idea about that when do not modify the hardware design of openwifi. 

Can you show me the way? 

Thank you very much again.

**Comment by JiaoXianjun** [comment]
You have two data sets of time stamp, one from csi, one from packet. Just do what ever you want!

**Comment by CaptainiFalcon** [comment]
Ohh, thanks a lot！

**Comment by CaptainiFalcon** [comment]
As shown in the figure below:

![Snipaste_2022-06-03_21-02-46](https://user-images.githubusercontent.com/46293421/171859739-9f887070-7407-4787-85c4-56ec2accaa5b.png)

Why do two or more csi have the same timestamp ?
