### ISSUE TITLE
Boot issue while using ADRV9364-Z7020 with FMC carrier board

### ISSUE THREAD

**Issue by sumanthraikar** [open-sdr/openwifi#206]
While booting with the files provided, I encountered the following error. Can anyone help me with this?

U-Boot 2014.07-dirty (Nov 20 2014 - 17:05:21)

Board:  Xilinx Zynq
I2C:   ready
DRAM:  ECC disabled 512 MiB
MMC:   zynq_sdhci: 0
SF: Detected N25Q256A with page size 256 Bytes, erase size 4 KiB, total 32 MiB
In:    serial
Out:   serial
Err:   serial
Net:   Gem.e000b000
Hit any key to stop autoboot:  0
Device: zynq_sdhci
Manufacturer ID: 3
OEM: 5344
Name: SD64G
Tran Speed: 50000000
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 59.5 GiB
Bus Width: 4-bit
Unknown command 'load' - try 'help'
Copying Linux from SD to RAM...
Unknown command 'load' - try 'help'
switch to partitions #0, OK
mmc0 is current device
Unknown command 'part' - try 'help'
env - environment handling commands

Usage:
env default [-f] -a - [forcibly] reset default environment
env default [-f] var [...] - [forcibly] reset variable(s) to their default values
env delete [-f] var [...] - [forcibly] delete variable(s)
env edit name - edit environment variable
env export [-t | -b | -c] [-s size] addr [var ...] - export environment
env import [-d] [-t | -b | -c] addr [size] - import environment
env print [-a | name ...] - print environment
env run var [...] - run commands in an environment variable
env save - save environment
env set [-f] name [arg ...]

Unknown command 'fstype' - try 'help'
(Re)start USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 1 USB Device(s) found
USB1:   usb1 wrong num MIO: 0, Index 1
lowlevel init failed
       scanning usb for storage devices... 0 Storage Device(s) found

USB device 0: unknown device
(Re)start USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 1 USB Device(s) found
USB1:   usb1 wrong num MIO: 0, Index 1
lowlevel init failed
       scanning usb for storage devices... 0 Storage Device(s) found
Gem.e000b000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Gem.e000b000: No link.
Unknown command 'pxe' - try 'help'
(Re)start USB...
USB0:   USB EHCI 1.00
scanning bus 0 for devices... 1 USB Device(s) found
USB1:   usb1 wrong num MIO: 0, Index 1
lowlevel init failed
       scanning usb for storage devices... 0 Storage Device(s) found
Gem.e000b000:0 is connected to Gem.e000b000.  Reconnecting to Gem.e000b000
Gem.e000b000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Gem.e000b000: No link.
Gem.e000b000:0 is connected to Gem.e000b000.  Reconnecting to Gem.e000b000
Gem.e000b000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
Gem.e000b000: No link.
zynq-uboot>

**Comment by JiaoXianjun** [comment]
Hello,

If I remember correctly, we never try to use 7020 with FMC https://wiki.analog.com/resources/eval/user-guides/adrv936x_rfsom/hardware#adrv9364-z7020_hardware . It is recommended that using 7035 with FMC/BOB and using 7020 with BOB:

Carrier Support

The ADRV9361-Z7035 supports all features on the [ADRV1CRR-FMC](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/ADRV1CRR-FMC.html) carrier board. The ADRV9364-Z7020 supports a subset of features because the Zynq Z7020 has fewer available user I/Os. For the ADRV9364-Z7020 it is recommended to use the [ADRV1CRR-BOB](https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/ADRV1CRR-BOB.html) carrier.
