### ISSUE TITLE
ZCU102 system.dts and modification of clocks property for openwifi modules.

### ISSUE THREAD

**Issue by A-T-Kristensen** [open-sdr/openwifi#227]
Hello! I have a question on the clocks property of the openwifi components in the zcu102 device tree file [https://github.com/open-sdr/openwifi/blob/master/kernel_boot/boards/zcu102_fmcs2/system.dts](https://github.com/open-sdr/openwifi/blob/master/kernel_boot/boards/zcu102_fmcs2/system.dts)

How come that the tx_dma, rx_dma, openofdm_tx_0, xpu_0, side_ch_0, ..., components all use clocks = <0x3 0x49>; (like [https://github.com/open-sdr/openwifi/blob/master/kernel_boot/boards/zcu102_fmcs2/system.dts#L2512](https://github.com/open-sdr/openwifi/blob/master/kernel_boot/boards/zcu102_fmcs2/system.dts#L2512)) which is fabric clock 2 (pl_clk2). In the hardware design, the clock used for openofdm_tx_0 etc. comes from the clk_wiz_0 component's 100 MHz clock.

I also noted that in the .dts file, the XPU only has 1 clock, but in the hardware design it has pl_clk0 on xpu_0/ps_clk and xpu_0/s00_axi_aclk from the 100 MHz clock from the clk_wiz_0. Same with the rx_intf block, it only references the <0x3 0x49> clock but not the 40 MHz clock from the  util_ad9361_divclk component in the hardware design.

What is the reason for this change and are there other modifications that have to be made to the .dts file?

Thank you!

**Comment by JiaoXianjun** [comment]
Hello,

Thanks for the feedback.
I believe it is due to that we haven't update the clock in .dts in time after we change the openwifi IP clock from the source of ARM to the source of RF (check the figure): https://github.com/open-sdr/openwifi-hw#modify-ip-cores

Since the 40MHz clock is from the fmcommsX board, and it is turned on anyway by ad9361 driver stuffs, so openwifi IP could always get 100MHz from that RF 40MHz via clk_wiz_0. That is why it works and (almost) irrelevant to the Linux operation on the clk.

**Comment by A-T-Kristensen** [comment]
Hi,

Thanks for the reply! So this means that in practice, the wrong clock in the .dts file has little effect as long as the real clock is guaranteed in the hardware?

**Comment by JiaoXianjun** [comment]
I am not a Linux expert. Hard to say.

To my understanding, Linux will try to operate the clock (set/on/off/etc.) according to the devicetree. So, for those hardwares that support Linux operation, I guess the clock information in .dts is important, such as those clocks related to ADI modules (AD9361, etc.). In our case, openwifi_ip clock is generated from one of the AD9361 clock module, and not controlled by PS. So, as long as Linux setup the AD9361 clock (according to the information of them in the .dts) correctly, openwifi_ip will get correct clock anyway, because this branch is pure hardware (no software control/on/off/set channel from PS).

**Comment by A-T-Kristensen** [comment]
Thank you for the quick reply. That makes it a bit more clear for me.
