### ISSUE TITLE
What is the approximate max-disance of openwifi that packages do not loss?

### ISSUE THREAD

**Issue by CaptainiFalcon** [open-sdr/openwifi#53]
When I put my laptop(with Linux) 100cm away from the  sender (board : zcu102_fmcs2), no package loss.
![ori_100cm](https://user-images.githubusercontent.com/46293421/105142617-c582a580-5b35-11eb-89bd-2e147be81169.png)

200cm away from the  sender (board : zcu102_fmcs2)：
![ori_200cm](https://user-images.githubusercontent.com/46293421/105142769-f1059000-5b35-11eb-8a57-c3a4b27bf901.png)

300cm away from the  sender (board : zcu102_fmcs2)：
![ori_300cm_sec](https://user-images.githubusercontent.com/46293421/105142856-07abe700-5b36-11eb-8b04-a544a85e282e.png)

I don't know if there is something wrong with my experimental environment or that's the way it should be.

Thanks！

**Comment by JiaoXianjun** [comment]
tcp or udp? can you share our your test command?

**Comment by CaptainiFalcon** [comment]
> tcp or udp? can you share our your test command?

iperf -c 192.168.13.5 -u -i 1 -t 30 -l 100 -b 400k
and
iperf -s -u -i 1

**Comment by JiaoXianjun** [comment]
Due to the limited TX power of ad9361 (for openwifi configuration, it is around 0 or several dBm), it won't reach long distance. You need PA (Power Amplifier) to boost the distance. Such as: 

https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/ad-trxboost1-ebz.html#eb-overview

**Comment by winfelin** [comment]
If we use an ideal PA, can openwifi theoretically reach 5km within the line of sight?
