### ISSUE TITLE
cfg80211 and mac80211 as modules in adi-linux-64

### ISSUE THREAD

**Issue by frestuc** [open-sdr/openwifi#67]
Hi all,

Is there any reason as to why mac80211 and cfg80211 are left as modules in adi-linux but they are instead baked into the kernel in adi-linux-64?

Thanks,
Francesco

**Comment by JiaoXianjun** [comment]
Hello,

No special reason. 

At some moment, we thought maybe some time we need to change the mac80211 and cfg80211, so keeping them as modules are more appropriate (no need to recompile the whole kernel).

Later on, when we add zcu102 support (64bit), we just keep them as part of kernel (the default kernel config) because we probably won't change them in the near future.

Hope this explains.

**Comment by frestuc** [comment]
Yes, thank you.
